apiVersion: v1
kind: Secret
metadata:
  name: workercontagemsecret
type: Opaque
data:
  ConnectionSqlServer: <STRING DE CONEXÃO DO SQL SERVER EM BASE 64>
  ConnectionAzureServiceBus: <STRING DE CONEXÃO PARA A FILA DO AZURE SERVICE BUS EM BASE 64>
  ConnectionApplicationInsights: <STRING DE CONEXÃO PARA DO APPLICATION INSIGHTS EM BASE 64>